#!/bin/zsh
ewmhstatus | dzen2 -ta l -fn Terminus-8 -fg "#A7884F" -bg "#141414" -h 16 -w 1200 -e mouse3:collapse &


~/.dzen/calendar | dzen2 -ta r -fn Terminus-8 -fg "#A7884F" -bg "#141414" -h 16 -w 126 -x 1200 -l 8 -e button1=togglecollapse &

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 3 --transparent true --alpha 0 --tint 0x141414 --height 16&

