#!/bin/zsh

    TODAY=$(expr `date +'%d'` + 0)
    MONTH=`date +'%m'`
    YEAR=`date +'%Y'`
while true 
    do 
    
         date +'%k:%M' 
         cal | sed -r -e "1,2 s/.*/^fg(white)&^fg()/" -e "s/(^| )($TODAY)($| )/\1^bg(red)^fg(#111)\2^fg()^bg()\3/"
         sleep 60
     
    done 


