#! /bin/zsh

hsetroot -fill /home/lumo/Kuvat/Taustat/current
dunst&
compton --config ~/.config/compton.conf &
urxvtd&
pa-applet&
unclutter&
sxhkd -c /home/lumo/.config/bspwm/sxhkdrc &

bspc desktop -n 1
bspc monitor -a 2 3 4 5 6 7 8 9 0 pad
bspc desktop pad -l monocle 

bspc config top_padding 16


bspc rule -a Gimp -d Eight --floating

bspc config split_ratio             0.50
bspc config border_width            1
bspc config window_gap              40
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focused_border_color    "#EDEFF2"
bspc config normal_border_color     "#8292B2"   
bspc config presel_border_color     "#8292B2"


exec /home/lumo/.config/dzen/bar
