#!/usr/bin/zsh
export PATH="$PATH:/home/lumo/scripts:/root/.gem/ruby/2.0.0/bin:/home/lumo/.gem/ruby/2.0.0/bin/"

xasetukset
 
xrdb ~/.config/Xresources
redshift -l 61.475514:23.774414 &

xcape&

export PANEL_FIFO=/home/nindwen/.tmp/bspwm-fifo

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
exec bspwm -c /home/nindwen/.config/bspwm/bspwmrc 
