#! /bin/sh
#
# Example panel for LemonBoy's bar

#COLOR_FOREGROUND='#00A3A6AB'
COLOR_FOREGROUND='#802b303b'
COLOR_BACKGROUND='#FF34322E'
COLOR_ACTIVE_MONITOR_FG='#FF34322E'
COLOR_ACTIVE_MONITOR_BG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_FG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_BG='#FF34322E'
COLOR_FOCUSED_OCCUPIED_FG='#FFF6F9FF'
COLOR_FOCUSED_OCCUPIED_BG='#FF5C5955'
COLOR_FOCUSED_FREE_FG='#FFF6F9FF'
COLOR_FOCUSED_FREE_BG='#FF6D561C'
COLOR_FOCUSED_URGENT_FG='#FF34322E'
COLOR_FOCUSED_URGENT_BG='#FFF9A299'
COLOR_OCCUPIED_FG='#FFA3A6AB'
COLOR_OCCUPIED_BG='#FF34322E'
COLOR_FREE_FG='#FF6F7277'
COLOR_FREE_BG='#FF34322E'
COLOR_URGENT_FG='#FFF9A299'
COLOR_URGENT_BG='#FF34322E'
COLOR_LAYOUT_FG='#FFA3A6AB'
COLOR_LAYOUT_BG='#FF34322E'
COLOR_TITLE_FG='#FFA3A6AB'
COLOR_TITLE_BG='#FF34322E'
COLOR_STATUS_FG='#FFA3A6AB'
COLOR_STATUS_BG='#FF34322E'

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			#sys_infos=" ${line#?} "
			;;
		T*)
			# xtitle output
			#title=" ${line#?} "
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos  ${name}   "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos  ${name}   "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{U$COLOR_FOREGROUND}%{+o} ▲ %{-o}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{U$COLOR_FOREGROUND}%{+o} △ %{-o}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{U$COLOR_FOREGROUND}%{+o} ▶ %{-o}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos} ▼ "
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos} ▽ "
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos} ▷ "
						;;
					L*)
						# layout
						#wm_infos="$wm_infos   ${name} "
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${title}%{c}${wm_infos}%{r}%{F#50ffffff}${sys_infos}%{F-}"
done
