#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
      for f in /etc/X11/xinit/xinitrc.d/*; do
            [ -x "$f" ] && . "$f"
      done
      unset f
fi

envfile="$HOME/.gnupg/gpg-agent.env"
if [[ -e "$envfile" ]] && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
      eval "$(cat "$envfile")"
else
      eval "$(gpg-agent --daemon --enable-ssh-support --write-env-file "$envfile")"
fi
export GPG_AGENT_INFO  # the env file does not contain the export statement
export SSH_AUTH_SOCK   # enable gpg-agent for ssh

session=${1:-2bwm}

case $session in
      test)
            exec xterm
            ;;
      bspwm) 
            exec /home/nindwen/.config/bspwm/init
            ;;
      wm)
            /home/nindwen/.config/wmutils/init
            ;;
      gnome)
            exec gnome-session
            ;;
      kde)
            exec startkde
            ;;
      xfce)
            exec startxfce4
            ;;
      xmonad)
            exec /home/nindwen/.config/xmonad/init
            ;;
      awe)
            exec /home/nindwen/.config/awesome/init
            ;;
      dwm)
            exec /home/nindwen/.config/dwm/init
            ;;
      2bwm)
            exec /home/nindwen/.config/2bwm/init
            ;;
esac
