#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
   for f in /etc/X11/xinit/xinitrc.d/*; do
      [ -x "$f" ] && . "$f"
   done
   unset f
fi

session=${1:-dwm}

case $session in
   test)
      exec xterm
      ;;
   bspwm) 
      exec /home/nindwen/.config/bspwm/init
      ;;
   wm)
      /home/nindwen/.config/wmutils/init
      ;;
   gnome)
      exec gnome-session
      ;;
   kde)
      exec startkde
      ;;
   dwm)
      exec /home/nindwen/.config/dwm/init
      ;;
esac
