#!/bin/sh



#trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


bspc control --subscribe > $PANEL_FIFO &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%H:%M' > "$PANEL_FIFO" &
panel_battery > "$PANEL_FIFO" &


cat "$PANEL_FIFO" | /home/lumo/.config/dzen/panel_bar | bar&
#cat "$PANEL_FIFO" | /home/lumo/.config/dzen/bspwm_panel | dzen2 -ta l -fn -lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1 -fg "#8292B2" -bg "#181512" -h 16 -w 1230 -e mouse3:collapse &


#~/.config/dzen/calendar | dzen2 -ta m -fn  -lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1 -fg "#8292B2" -bg "#1b1b1b" -h 16 -w 136 -x 1230 -l 8 -e button1=togglecollapse &

#trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 3 --transparent true --alpha 0 --tint 0x141414 --height 16&

