#!/bin/zsh
ewmhstatus | dzen2 -ta l -fn -lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1 -fg "#8292B2" -bg "#181512" -h 16 -w 1230 -e mouse3:collapse &


~/.config/dzen/calendar | dzen2 -ta m -fn  -lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1 -fg "#8292B2" -bg "#181512" -h 16 -w 136 -x 1230 -l 8 -e button1=togglecollapse &

#trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 3 --transparent true --alpha 0 --tint 0x141414 --height 16&

