#! /bin/sh
#
# Example panel for dzen2

font_family='-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1'
font_size=11

color1=#C8CACC
color2=red

adaptive_centering=0
screen_width=$(sres -W)
NORMIFS=$IFS
FIELDIFS=':'
PADDING=' '

while getopts 'af:s:' opt ; do
    case "$opt" in
        a)
            adaptive_centering=1
            ;;
        f)
            font_family=$OPTARG
            ;;
        s)
            font_size=$OPTARG
            ;;
    esac
done

shift $((OPTIND - 1))

while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos=""
            ;;
        T*)
            # xtitle output
            title="^fg($COLOR_TITLE_FG)^bg($COLOR_TITLE_BG)${PADDING}${line#?}${PADDING}^fg()^bg()"
            ;;
        W*)
            # bspwm internal state
            wm_infos="$PADDING"
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                FG=$color1
                                BG=
                                ;;
                            F*)
                                # focused free desktop
                                FG=$color1
                                BG=
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$color1
                                BG=
                                ;;
                            o*)
                                # occupied desktop
                                FG=
                                BG=
                                ;;
                            f*)
                                # free desktop
                                FG=#181512
                                BG=
                                ;;
                            u*)
                                # urgent desktop
                                FG=red
                                BG=
                                ;;
                        esac
                        wm_infos="${wm_infos}^fg(${FG})^bg(${BG})${name}${PADDING}"
                        ;;
                    L*)
                        # layout
                        layout=
                        wm_infos="${wm_infos}^fg()^bg()${PADDING}${PADDING}^fg($COLOR_LAYOUT_FG)^bg($COLOR_LAYOUT_BG)${PADDING}$layout${PADDING}"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    set -- $(printf '%s\0%s\0%s' "$wm_infos" "$title" "$sys_infos" | sed 's/\^[a-z]\+([^)]*)//g' | xargs -0 txtw -f "$font_family" -s "$font_size")
    left_width=$1
    center_width=$2
    right_width=$3
    left_indent=0
    right_indent=$((screen_width - right_width))
    available_center=$((screen_width - (left_width + right_width)))
    if [ $available_center -lt $center_width ] ; then
        center_indent=$((left_indent + left_width))
    else
        if [ $adaptive_centering -eq 1 ] ; then
            center_indent=$((left_width + (available_center - center_width) / 2))
        else
            center_indent=$(( (screen_width - center_width) / 2 ))
        fi
    fi
    printf "%s\n" "^pa($center_indent)$title^pa($left_indent)$wm_infos^pa($right_indent)$sys_infos"
done
