#!/bin/zsh

    TODAY=$(expr `date +'%d'` + 0)
    MONTH=`date +'%m'`
    echo "^p(_CENTER)^i(/home/lumo/.gitconf/master/WM/dzen/icons/clock.xbm) $(date +'%k:%M')" 
    YEAR=`date +'%Y'`
         cal | sed -r -e "1,2 s/.*/^fg(white)&^fg()/" -e "s/(^| )($TODAY)($| )/\1^bg(red)^fg(#111)\2^fg()^bg()\3/"   
sleep 30 
while true 
    do 
    
         echo "^tw()^p(_CENTER)^i(/home/lumo/.gitconf/master/WM/dzen/icons/clock.xbm) $(date +'%k:%M')" 
         sleep 30
     
    done 


