#!/bin/zsh
memused=$(free -m | awk 'NR == 3 {gsub(/%/,""); print $3}')
mem=$((($memused)*100/3822))
proc=$(cat /proc/loadavg | cut -d " " -f 1)
((proc = 100*$proc))
left="\\f3⭥\\f1 $(($proc))%  \\f3⭦\\f1 $mem%  \\f3▤\\f1 $(df -h | grep "sda5" | awk '{print $5}')"
middle="\\f3♪\\f1 $(mpc current)"
day=$(date +%A)
right="\\f3❐\\f1 ${(C)day[1]}$day[2,-1] $(date +"%e.%m")"

printf "%s\n" "\\l $left\\c$middle\\r$right " | bar -p
