#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
				B*)
						sys_infos2=" \\f2energia \\f3${line#?} "
						;;
        S*)
            sys_infos="\\r$sys_infos2 \\f2aika\\f3 ${line#?}  \\fr\\f1"
            ;;
        T*)
            title="\\l\\f1 \\f3 $(echo ${line#?}|cut -c -90) \\f2paikka "
            ;;
        W*)
            wm_infos="\\c"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                if [[ $name != "pad" ]]; then
                    #name=" • "
                    case $item in
                        [OU]*)
                            # active desktop
                            wm_infos="$wm_infos\\f3\\u2\\b4   $name   \\br\\ur\\fr"
                            ;;
                        F*)
                            wm_infos="$wm_infos\\f2\\u2\\b4   $name   \\br\\ur\\fr"
                            ;;
                        o*)
                            # inactive but occupied desktop
                            wm_infos="$wm_infos\\f3   $name   \\fr"
                            ;;
                        f*)
                            # inactive desktop
                            wm_infos="$wm_infos\\f2   $name   \fr"
                            ;;
                        u*)
                            # urgent desktop
                            wm_infos="$wm_infos \\f6   $name   \\fr "
                            ;;
                        L*)
                            # layout
    #                       layout=$(printf "%s" " • " | sed 's/\(.\).*/\U\1/')
                  			layout=""
                            wm_infos="$wm_infos \\f0$layout\\fr"
                            ;;
                        esac
                fi
                shift
            done
            ;;
    esac
    printf "%s\n" "$title  $wm_infos  $sys_infos"
done
