#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        S*)
            sys_infos="\\r\\f3⭧ \\f1${line#?}\\fr  "
            ;;
        T*)
            title="\\l\\f3\\ab   ❤  \\ac dmenu_run -y 22 -w 300 -l 6 \\ae\\f1$(echo ${line#?}|cut -c -90) "
            ;;
        W*)
            wm_infos="\\c"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                if [[ $name != "pad" ]]; then
                    #name=" • "
                    case $item in
                        [OU]*)
                            # active desktop
                            wm_infos="$wm_infos\\ab\\u3\\f1 • \\ac bspc desktop -f ${name}\\fr\\br\\ur\\ae"
                            ;;
                        F*)
                            wm_infos="$wm_infos\\u3\\f0\\ab • \\ac bspc desktop -f ${name} \\ae\\fr\\br\\ur"
                            ;;
                        o*)
                            # inactive but occupied desktop
                            wm_infos="$wm_infos\\f1\\ab • \\ac bspc desktop -f ${name}\\ae\\fr"
                            ;;
                        f*)
                            # inactive desktop
                            wm_infos="$wm_infos\\f0\\ab • \\ac bspc desktop -f ${name}\\ae\\fr"
                            ;;
                        u*)
                            # urgent desktop
                            wm_infos="$wm_infos \\u3\\f6\\ab • \\ac bspc desktop -f ${name}\\ae \\ur\\fr "
                            ;;
                        L*)
                            # layout
    #                       layout=$(printf "%s" " • " | sed 's/\(.\).*/\U\1/')
                  			layout=""
                            wm_infos="$wm_infos \\b4\\f0$layout\\br\\fr"
                            ;;
                        esac
                fi
                shift
            done
            ;;
    esac
    printf "%s\n" "$title  $wm_infos  $sys_infos"
done
