#!/usr/bin/env python

import sys
import re
from colour import Color

def shift(object):
    col=object.group(0)
    c=Color(col)
    c.hue=c.hue+float(sys.argv[2])
    return c.hex

f = open(sys.argv[1],"r")
result = ""

for line in f:
    result = result + re.sub('\#[0-9A-Fa-f]{6}',shift,line)

print(result)
