#!/bin/zsh

rm ~/.gitconf/master/System/colors/$1
active=$(python ~/scripts/generatecolors.py $1 $3)
bspc config normal_border_color $active
echo "bspc config normal_border_color '$active'" > ~/.config/bspwm/maincolor

sed "53s/.*/color: $active !important;/" ~/.mozilla/firefox/9xl5fsa3.default/chrome/userChrome.css > ~/.mozilla/firefox/9xl5fsa3.default/chrome/userChrome2.css
cp ~/.mozilla/firefox/9xl5fsa3.default/chrome/userChrome2.css ~/.mozilla/firefox/9xl5fsa3.default/chrome/userChrome.css

cd ~/.gitconf/master/System/colors/
rm current
ln -s $1 current 
xrdb ~/.config/Xresources

cd ~/Kuvat/Taustat
rm current
ln -s $1 current
hsetroot -$2 $1

~/bin/bar/palette.pl ~/.gitconf/master/System/colors/current > ~/bin/bar/colors.h
cd ~/bin/bar
make && sudo make install
pkill bar
~/.config/dzen/bar&
