#!/bin/bash

# Upload a file to salaatti.usvs.xyz
# Usage: salaatti file.smt

STRING=$(curl -s -F "file=@$1" salaatti.usvs.xyz)
IFS=' ' read -r -a array <<< "$STRING"
echo "http://salaatti.usvs.xyz/${array[-1]}"
