#!/bin/sh

# Show menu for commonly used apps

valimenu << EOF | sh
qutebrowser
firefox
gimp
steam
google-chrome-beta
zathura
minecraft
lotro
inkscape
mypaint
blender
xasetukset
olelol
salaisuudet
netbeans
wesnoth
EOF
