
set encoding=utf-8
set path=.,,inc,src,/usr/include,/usr/local/include
set backupdir=~/.vimtmp,.
set directory=~/.vimtmp,.
set undofile
set undodir=~/.vim/undo
set undolevels=5000
set laststatus=0

set tabstop=2
set shiftwidth=2
set hidden
set confirm
set expandtab
set dir=~/.vimtmp

map - <Nop>
nmap j gj
nmap k gk
let mapleader="-"
nmap <Leader><Space> :noh<CR>
nmap <Space> :bnext<CR>
nmap <BS> :bprevious<CR>
nnoremap K i<CR><Esc>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
execute pathogen#infect()
call pathogen#helptags()

call plug#begin('~/.vim/plugged')
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()

set t_Co=16
set background=dark
colorscheme hybrid

noremap  <Up> <NOP>
noremap! <Up> <NOP>
noremap  <Down> <NOP>
noremap! <Down> <NOP>
noremap  <Left> <NOP>
noremap! <Left> <NOP>
noremap  <Right> <NOP>
noremap! <Right> <NOP>
