#!/bin/sh



~/bin/xasetukset
 
redshift -l 61.475514:23.774414 &

xcape&
unset DBUS_SESSION_BUS_ADDRESS
hsetroot -tile ~/usr/wallpapers/current &
dunst&
compton --config ~/.config/compton.conf &
unclutter -noevents -root -idle 1 &
sxhkd &

# Statusbar loop
while true; do
      xsetroot -name "$( date +"%F %R" )"
      sleep 1m    # Update time every minute
done &

# relaunch DWM if the binary changes, otherwise bail
csum=$(sha1sum $(which dwm))
new_csum=""
while true
do
      if [ "$csum" != "$new_csum" ]
      then
            csum=$new_csum
            dwm >> lol 2>> lol
      else
            exit 0
      fi
      new_csum=$(sha1sum $(which dwm))
      sleep 0.5
done
